
// ********RoostGPT********
/*
Test generated by RoostGPT for test spring-boot-crud using AI Type Azure Open AI and AI Model Inference

ROOST_METHOD_HASH=create_3f3d045f36
ROOST_METHOD_SIG_HASH=create_65031a56c6

```plaintext
Scenario 1: Successful Creation of a New App

Details:
  TestName: createNewAppSuccessfully
  Description: This test checks the successful creation of a new app using valid input data.
Execution:
  Arrange: Prepare a valid AppDTO object and mock the AppService to return a unique app ID.
  Act: Invoke the create method with the valid AppDTO and UriComponentsBuilder.
  Assert: Verify that the response status is HttpStatus.CREATED and the Location header is correctly set.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 2: Creation of a New App with Invalid Input Data

Details:
  TestName: createNewAppWithInvalidInput
  Description: This test checks the behavior when attempting to create a new app with invalid input data.
Execution:
  Arrange: Prepare an AppDTO object with invalid data (e.g., missing required fields) and mock the AppService.
  Act: Invoke the create method with the invalid AppDTO and UriComponentsBuilder.
  Assert: Verify that a ValidationException or similar is thrown.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 3: Creation of a New App with Service Exception

Details:
  TestName: createNewAppWithServiceException
  Description: This test checks the behavior when the service throws an exception during app creation.
Execution:
  Arrange: Prepare a valid AppDTO object and mock the AppService to throw an exception when createNewApp is called.
  Act: Invoke the create method with the valid AppDTO and UriComponentsBuilder.
  Assert: Verify that the exception is correctly handled and an appropriate error response is returned.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 4: Creation of a New App with Null UriComponentsBuilder

Details:
  TestName: createNewAppWithNullUriComponentsBuilder
  Description: This test checks the behavior when the UriComponentsBuilder is null.
Execution:
  Arrange: Prepare a valid AppDTO object and pass null as the UriComponentsBuilder.
  Act: Invoke the create method with the valid AppDTO and null UriComponentsBuilder.
  Assert: Verify that a NullPointerException or similar is thrown.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 5: Creation of a New App with Null AppDTO

Details:
  TestName: createNewAppWithNullAppDTO
  Description: This test checks the behavior when the AppDTO is null.
Execution:
  Arrange: Pass null as the AppDTO and a valid UriComponentsBuilder.
  Act: Invoke the create method with null AppDTO and valid UriComponentsBuilder.
  Assert: Verify that a NullPointerException or similar is thrown.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.

Scenario 6: Creation of a New App with Existing App Details

Details:
  TestName: createNewAppWithExistingDetails
  Description: This test checks the behavior when attempting to create a new app with details that already exist.
Execution:
  Arrange: Prepare an AppDTO object with details that already exist in the system and mock the AppService to return a unique app ID.
  Act: Invoke the create method with the existing AppDTO and UriComponentsBuilder.
  Assert: Verify that the response status is HttpStatus.CREATED and the Location header is correctly set, even though the details already exist.
Validation:
  Clarify what the assertion aims to verify and the reason behind the expected result.
  Elaborate on the significance of the test in the context of application behavior or business logic.
```
*/

// ********RoostGPT********

package br.com.example.davidarchanjo.controller;

import br.com.example.davidarchanjo.model.dto.AppDTO;
import br.com.example.davidarchanjo.service.AppService;
import com.github.javafaker.Faker;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.util.UriComponentsBuilder;
import javax.validation.ConstraintViolationException;
import javax.validation.Valid;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;
import lombok.AllArgsConstructor;
import org.springframework.http.HttpHeaders;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.util.UriComponents;

class AppControllerCreateTest {

	@Mock
	private AppService service;

	@InjectMocks
	private AppController appController;

	private Faker faker;

	@BeforeEach
	void setUp() {
		MockitoAnnotations.openMocks(this);
		faker = new Faker();
	}

	@Test
	@Tag("valid")
	void createNewAppSuccessfully() {
		AppDTO dto = new AppDTO();
		dto.setName(faker.app().name());
		dto.setVersion(faker.app().version());
		when(service.createNewApp(any(AppDTO.class))).thenReturn(1L);
		UriComponentsBuilder uriComponentsBuilder = UriComponentsBuilder.fromPath("/api/v1/apps/1");
		ResponseEntity<?> response = appController.create(dto, uriComponentsBuilder);
		assertEquals(HttpStatus.CREATED, response.getStatusCode());
		assertNotNull(response.getHeaders().getLocation());
		assertEquals("http://localhost/api/v1/apps/1", response.getHeaders().getLocation().toString());
	}

	@Test
	@Tag("invalid")
	void createNewAppWithInvalidInput() {
		AppDTO dto = new AppDTO();
		dto.setName(null);
		dto.setVersion(null);
		UriComponentsBuilder uriComponentsBuilder = UriComponentsBuilder.fromPath("/api/v1/apps/1");
		assertThrows(ConstraintViolationException.class, () -> appController.create(dto, uriComponentsBuilder));
	}

	@Test
	@Tag("invalid")
	void createNewAppWithServiceException() {
		AppDTO dto = new AppDTO();
		dto.setName(faker.app().name());
		dto.setVersion(faker.app().version());
		when(service.createNewApp(any(AppDTO.class))).thenThrow(new RuntimeException("Service Exception"));
		UriComponentsBuilder uriComponentsBuilder = UriComponentsBuilder.fromPath("/api/v1/apps/1");
		assertThrows(RuntimeException.class, () -> appController.create(dto, uriComponentsBuilder));
	}

	@Test
	@Tag("invalid")
	void createNewAppWithNullUriComponentsBuilder() {
		AppDTO dto = new AppDTO();
		dto.setName(faker.app().name());
		dto.setVersion(faker.app().version());
		assertThrows(NullPointerException.class, () -> appController.create(dto, null));
	}

	@Test
	@Tag("invalid")
	void createNewAppWithNullAppDTO() {
		UriComponentsBuilder uriComponentsBuilder = UriComponentsBuilder.fromPath("/api/v1/apps/1");
		assertThrows(NullPointerException.class, () -> appController.create(null, uriComponentsBuilder));
	}

	@Test
	@Tag("valid")
	void createNewAppWithExistingDetails() {
		AppDTO dto = new AppDTO();
		dto.setName(faker.app().name());
		dto.setVersion(faker.app().version());
		when(service.createNewApp(any(AppDTO.class))).thenReturn(1L);
		UriComponentsBuilder uriComponentsBuilder = UriComponentsBuilder.fromPath("/api/v1/apps/1");
		ResponseEntity<?> response = appController.create(dto, uriComponentsBuilder);
		assertEquals(HttpStatus.CREATED, response.getStatusCode());
		assertNotNull(response.getHeaders().getLocation());
		assertEquals("http://localhost/api/v1/apps/1", response.getHeaders().getLocation().toString());
	}

}